### ISSUE TITLE
media-ccc plugin stopped working completely

### ISSUE THREAD

**Issue by Wend1go** [voc/plugin.video.media-ccc-de#25]
The (fresh installed) plug-in stopped working completely.
Upon opening, it shows the loading circle for about 30 seconds and then quits.

LibreElec 9.1.502
(also on current OSMC don't know the version)

```
2019-11-10 13:41:31.452 T:1542452096  NOTICE: LoadJpeg: unable to load /storage/.kodi/addons/plugin.video.media-ccc-de/fanart.jpg
2019-11-10 13:42:33.894 T:1239548800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 197, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 22, in show_dir
                                                data = get_index_data()
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 156, in get_index_data
                                                return http.fetch_data('conferences')['conferences']
                                              File "/storage/.kodi/addons/plugin.video.media-ccc-de/resources/lib/http.py", line 21, in fetch_data
                                                return req.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
2019-11-10 13:42:33.931 T:1231156096   ERROR: GetDirectory - Error getting plugin://plugin.video.media-ccc-de/
2019-11-10 13:42:33.933 T:1936965648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.media-ccc-de/) failed
2019-11-10 13:42:34.011 T:1908933504  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2019-11-10 13:42:50.778 T:1936965648   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-11-10 13:42:56.016 T:1239548800   ERROR: Unable to find plugin
2019-11-10 13:42:56.016 T:1239548800   ERROR: GetDirectory - Error getting plugin://
2019-11-10 13:42:56.018 T:1936965648   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2019-11-10 13:43:00.660 T:1936965648   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
```

**Comment by TobiX** [comment]
Cannot reproduce in either LibreElec 9.0.2, LibreElec 9.1.502 or Debian unstable.

- [ ] Can you rule out a network problem?
- [ ] Does https://api.media.ccc.de/public/conferences return valid JSON for you?
- [ ] Did you switch to insecure connections in the plugin settings?
- [ ] Is your SD card okay? (the first line suggests maybe some filesystem problems...)

**Comment by a-tze** [comment]
JFI media.ccc.de currently has some severe issues that lead to timeouts or 503 responses. chances are high that this is the root cause.

**Comment by Wend1go** [comment]
1) Internet connection is present, other plugins can play videos from the internet without any issues
2) I'll try to access the url via ssh and report back
3) Nothing was changed, the default settings are still set
4) I could install LibreElec without any issues on the card and other plugins are working fine. Didn't run an explicit test on the card though

**Comment by Wend1go** [comment]
2. It is indeed possible to access the url and download the json file from the PI3B

It looks like only the version from the Kodi repository has this issue.
After downloading and installing the zip version, the plugin runs fine.

**Comment by TobiX** [comment]
I'll note this down as "network issues", if the problem reappears, please try to get a [log file](https://kodi.wiki/view/Log_file) (You can send the log via mail, IRC or Twitter private message if it might contain personal data)
